export const DRAWER_TOGGLED = "DRAWER_TOGGLED"
export const SET_CATEGORIES = "SET_CATEGORIES"

export const GET_RESOURCES = "GET_RESOURCES"

export const RESOURCES_SEARCH_TEXT_UPDATED = "RESOURCES_SEARCH_TEXT_UPDATED"

export const GET_EXCHANGE_DATA = "GET_EXCHANGE_DATA"

export const SET_COMPANIES = "SET_COMPANIES"

export const EDIT_COMPANY_FORM_UPDATED = "EDIT_COMPANY_FORM_UPDATED"
export const EDIT_COMPANY_FORM_LOADED = "EDIT_COMPANY_FORM_LOADED"
export const EDIT_COMPANY_FORM_SAVE_SUCCEEDED =
  "EDIT_COMPANY_FORM_SAVE_SUCCEEDED"

export const NEW_COMPANY_FORM_CLEARED = "NEW_COMPANY_FORM_CLEARED"
export const NEW_COMPANY_FORM_UPDATED = "NEW_COMPANY_FORM_UPDATED"
export const NEW_COMPANY_SAVE_SUCCEEDED = "NEW_COMPANY_SAVE_SUCCEEDED"
export const NEW_COMPANY_SAVE_FAILED = "NEW_COMPANY_SAVE_FAILED"

export const COMPANY_DELETE_SUCCEECED = "COMPANY_DELETE_SUCCEECED"
