export const DRAWER_TOGGLED = "DRAWER_TOGGLED"
export const SET_CATEGORIES = "SET_CATEGORIES"

export const GET_RESOURCES = "GET_RESOURCES"

export const RESOURCES_SEARCH_TEXT_UPDATED = "RESOURCES_SEARCH_TEXT_UPDATED"

export const GET_EXCHANGE_DATA = "GET_EXCHANGE_DATA"
