export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'
export const SET_CATEGORIES = 'SET_CATEGORIES'

export const GET_RESOURCES = 'GET_RESOURCES'

export const RESOURCES_SEARCH_TEXT_UPDATED = 'RESOURCES_SEARCH_TEXT_UPDATED'

export const GET_EXCHANGE_DATA = 'GET_EXCHANGE_DATA'

export const GET_COMPANIES = 'GET_COMPANIES'
export const EDIT_COMPANY_FORM_UPDATED = 'EDIT_COMPANY_FORM_UPDATED'

export const EDIT_COMPANY_FORM_LOADED = 'EDIT_COMPANY_FORM_LOADED'
export const EDIT_COMPANY_FORM_SAVE_SUCCEEDED =
  'EDIT_COMPANY_FORM_SAVE_SUCCEEDED'
